name: lint
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Check code style with ruff
      run: uv run ruff check .
    - name: Check formatting with black
      run: uv run black --check .
    - name: Check import order with isort
      run: uv run isort --check-only .
    - name: Check types with pyright
      run: uv run pyright .
