name: linter
on:
  pull_request:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Run ruff
      run: uv run ruff check .
    - name: Run black
      run: uv run black --check .
    - name: Run isort
      run: uv run isort --check-only .
    - name: Run flake8
      run: uv run flake8 .
    - name: Run pyright
      run: uv run pyright .
